test2/test2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    # url(r'^web/', include(('website.urls', 'website'), namespace='website')), # namespace 反向解析使用
    url(r'^web/', include('website.urls', namespace='website')),
]

test2/website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    url(r'^$', views.index),
    url(r'chenjinyu/', views.chenjinyu),
    url(r'dels', views.dels),

    # url(r'^herolist/(\d+)/$', views.lists, name='lists'),



    # url(r'^herolist(?P<pindex>[0-9]*)/$', views.lists, name='lists'),
    # url(r'^(?P<id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^herolist2/$', views.listspage, name='listspage'),

    url(r'^urlceshi/$', views.urlceshi),
    url(r'^urlanalysis/(\d+)/(\d+)$', views.urlanalysis, name='ceshi1'), #反向解析带参数
    # url(r'^urlanalysis/$', views.urlanalysis, name='ceshi1'), #反向解析不带参数
    url(r'^urlanalysis2/(?P<id>\d+)/(?P<age>\d+)$', views.urlanalysis2, name='ceshi2'), #反向解析带参数

    url(r'^imgstatic/$', views.imgStatic),
]



test2/website/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class WebsiteBookinfo(models.Model):
    btitle = models.CharField(max_length=20)
    pub_date = models.DateTimeField()
    bread = models.IntegerField()
    bcommet = models.IntegerField()
    isdelete = models.IntegerField(db_column='isDelete')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'website_bookinfo'


class WebsiteCeshi(models.Model):
    name = models.CharField(max_length=50)
    sex = models.IntegerField()
    addr = models.TextField()
    age = models.IntegerField()
    pub_date = models.DateTimeField()
    addtime = models.DateTimeField(db_column='addTime')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'website_ceshi'


#############################
# 管理器


class WebsiteChenjinyuManager(models.Manager):
    def get_queryset(self):  # 自定义管理师 有过滤作用
        return super(WebsiteChenjinyuManager, self).get_queryset().filter(status=True)


class WebsiteChenjinyu(models.Model):
    chen = models.CharField(max_length=50)
    jin = models.TextField()
    yu = models.IntegerField()
    status = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'website_chenjinyu'
    # 两种方式
    books1 = models.Manager()
    books2 = WebsiteChenjinyuManager()

#############################


class WebsiteHeroinfo(models.Model):
    hname = models.CharField(max_length=10)
    hgender = models.IntegerField()
    hcontent = models.CharField(max_length=1000)
    isdelete = models.IntegerField(db_column='isDelete')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'website_heroinfo'


class WebsiteYu(models.Model):
    name = models.CharField(max_length=20)
    age = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'website_yu'

test2/website/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.db.models import Max, F, Q

from django.core.paginator import Paginator  # 分页模块


# Create your views here.
def index(request):
    context = {}
    return render(request, 'websites/index.html', context)


def chenjinyu(request):
    # list = WebsiteChenjinyu.books1.filter(Q(pk__lt=4))
    list = WebsiteChenjinyu.books2.filter(Q(pk__lt=4))  # 自定义管理器使用
    # re1 = WebsiteChenjinyu.books2.get(id=2)
    re1 = WebsiteChenjinyu.books2.filter(id=2)
    re2 = WebsiteChenjinyu.books2.filter(id=2).first()
    # print(re1)

    context = {'list1': list, 'get1': re1, 'get2': re2}
    return render(request, 'websites/chenjinyu.html', context)


def dels(request):
    # re = WebsiteChenjinyu.books1.filter(id=11).delete()
    re = WebsiteChenjinyu.books2.filter(id=2)
    if re.exists():
        return HttpResponse(re)
    else:
        return HttpResponse(re.exists())


# 分页功能实现
def listspage(request):
    pindex = request.GET.get('pindex', '1')
    list = WebsiteChenjinyu.books2.order_by('-id')  # 倒序 使用 - 号
    # list = WebsiteChenjinyu.books2.all()
    paginator = Paginator(list, 5, 2)
    numbers = paginator.num_pages
    page = paginator.page(int(pindex))
    context = {'page': page, 'numbers': numbers}
    return render(request, "websites/borrow_show2.html", context)


################ # 反向解析测试
def urlceshi(request):
    return render(request, 'websites/urlceshi.html')


def urlanalysis(request, id1, id2):
    return render(request, 'websites/urlanalysis.html')


def urlanalysis2(request, id, age):
    context = {'id': id, 'age': age}
    return render(request, 'websites/urlanalysis2.html', context)

################ # 静态文件

def imgStatic(request):

    return render(request, 'statics/imgstatic.html')

test2/templates/websites/borrow_show2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分页</title>
</head>
<style>
    #page-normal{
	color:#ff9655;
	text-align:center;
	font-size:0px;
}

#page-normal a{
	border:1px solid #ff9600;
	padding:5px 7px;
	color:#ff9655;
	text-decoration:none;
	font-size:15px;
	margin-right:10px;
}

#page-normal a:hover{
	border:1px solid #ff9600;
	padding:5px 7px;
	background-color:#ffbe94;
}

#page-prev{
	border:1px solid #ff9600;
	color:#ff9600;
	padding:5px 7px;
	font-size:15px;
	margin-right:10px;
	}

.page-prevs{
	border:1px solid #ff9600;
	color:#ff9600;
	padding:5px 7px;
	font-size:15px;
	margin-right:10px;
	}

#page-prev i{
	margin-right:5px;
	}

#page-next i{
	margin-left:5px;
	}

#page-current{
	border:1px solid #ff9600;
	padding:5px 7px;
	background-color:#ffbe94;
	font-size:15px;
	margin-right:10px;
}

#page-ellipsis{
	font-size:15px;
	margin-right:10px;
}
</style>
<body>





<ul>
    {% for hero in page %}
        <li>{{ hero.id }}</li>
    {% endfor %}
</ul>

<!--<hr>-->
<!--{% for index in page.paginator.page_range %}-->
<!--    {% if index == page.number %}-->
<!--{{ index }}-->
<!--    {% else %}-->
<!--<a href="/web/herolist/{{ index }}">{{ index }}</a>-->
<!--    {% endif %}-->
<!--{% endfor %}-->


<div id="page-normal">

    {% if page.has_previous %}
    <a class="page-prevs" href="/web/herolist2?pindex=1"><i></i>首页({{ numbers }})</a>
    <a id="page-prev" href="/web/herolist2?pindex={{ page.previous_page_number }}"><i></i>上一页</a>
    {% else %}
    <span class="page-prevs"><i></i>首页({{ numbers }})</span>
    <span id="page-prev"><i></i>上一页</span>
    {% endif %}
    {% for index in page.paginator.page_range %}

            {% if index == page.number %}
            <span id="page-current">{{ index }}({{ page.number|add:-4 }})</span>
            {% else %}
                {% if index > page.number|add:-4  and index < page.number|add:4 %}
                    <a href="/web/herolist2?pindex={{ index }}">{{ index }}</a>
                {% endif %}

            {% endif %}

    {% endfor %}


    {% if page.has_next %}
    <a id="page-next" href="/web/herolist2?pindex={{ page.next_page_number }}">下一页<i></i></a>

    <a class="page-prevs" href="javascript:"><i></i>共{{ numbers }} 页</a>

 <form action="/web/herolist2" method="get" style="float:right;">
    <span class="page-prevs" href="javascript:">
        <i></i>要到达 <input type="text" style="width: 30px;" value="{{ page.number }}" name="pindex"> 页
    </span>
        <span class="page-prevs" href="javascript:"><input type="submit" value="确定"></span>
    </form>


 <span class="page-prevs" href="javascript:">
        <i></i>要到达 <input type="text" style="width: 30px;" value="{{ page.number }}"> 页
    </span>
        <span class="page-prevs" ><input type="submit" value="确定"></span>



    <a class="page-prevs" href="/web/herolist2?pindex={{ numbers }}"><i></i>尾页</a>
    {% else %}

    <a class="page-prevs" href="javascript:"><i></i>下一页</a>
    <a class="page-prevs" href="javascript:"><i></i>共{{ numbers }} 页</a>

    <span class="page-prevs" href="javascript:"><i></i>要到达 <input type="text" style="width: 30px;" value="{{ page.number }}"> 页</span>


    <a class="page-prevs" href="javascript:"><i></i>尾页</a>
    {% endif %}

</div>




</body>
</html>

test2/templates/websites/chenjinyu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>chenjinyu</title>
</head>
<body>
chenjinyu
<h1>{{ get2.chen }} -- {{ get2.jin }} -- {{ get2.yu }}</h1>


<h1>{{ get1.0.chen }} -- {{ get1.0.jin }} -- {{ get1.0.yu }}</h1>

{% for gets in get1 %}
<h1>{{ gets.chen }} -- {{ gets.jin }} -- {{ gets.yu }}</h1>
{% endfor %}

<ul>
{% for book in list1 %}
<li>{{ book.id }} -- {{ book.chen }}--{{ book.jin }}--{{ book.yu }}</li>
{% endfor %}
</ul>
</body>
</html>

test2/templates/websites/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>后台首页</title>
</head>
<body>
<h1>后台首页</h1>
</body>
</html>

test2/templates/websites/urlanalysis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>反向解析2</title>
</head>
<body>
反向解析2  访问到了
</body>
</html>

test2/templates/websites/urlanalysis2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>反向解析2  带参数</title>
</head>
<body>
反向解析2  带参数
{{ id }} ---- {{ age }}
</body>
</html>

test2/templates/websites/urlceshi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>反向解析测试1</title>
</head>
<body>
<h1>反向解析测试1</h1>
<a href="{% url 'website:ceshi1' '111' '222' %}">测试1</a>
<a href="{% url 'website:ceshi2' id='1' age='22' %}">测试1</a>
6666666
</body>
</html>